version: "3"

services:
    mongo3:
        image: mongo:3.2
        ports:
            - "27022:27017"
        restart: always

    mongo2:
        image: mongo:3.2
        ports:
            - "27021:27017"
        restart: always

    mongo1:
        image: mongo:3.2
        ports:
            - "27020:27017"
        restart: always
