version: "3"

services:
    mongo3:
        image: mongonode
        build: ./mongonode
        ports:
            - "27022:27017"
        restart: always

    mongo2:
        image: mongonode
        ports:
            - "27021:27017"
        restart: always

    mongo1:
        image: mongonode
        ports:
            - "27020:27017"
        restart: always

    mongosetup:
        image: mongosetup
        build: ./mongosetup
